In [1]:
import numpy as np

## Creating arrays

In [2]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
b = np.array([[1], [2], [3], [4], [5]])
print(b)
print(type(b))
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
<class 'numpy.ndarray'>
(5, 1)


In [42]:
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c)
print(c.shape)
print(c[1][1])
print(c.T)

[[1 2 3]
 [4 5 6]]
(2, 3)
5
[[1 4]
 [2 5]
 [3 6]]


### Creating array of Zeros, Ones, or Custom Array

In [5]:
a = np.zeros((3, 3))
print(a)

b = np.ones((2, 3))
print(b)

c = np.full((3, 2), 5)
print(c)

d = np.eye(4)
print(d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
randomMatrix = np.random.random((2, 3))
print(randomMatrix)

print(randomMatrix[:, 1])
randomMatrix[1, 1:] = 1

print(randomMatrix)

[[0.24202594 0.70055495 0.03767687]
 [0.37732366 0.6750766  0.65059295]]
[0.70055495 0.6750766 ]
[[0.24202594 0.70055495 0.03767687]
 [0.37732366 1.         1.        ]]


In [7]:
z = np.zeros((3, 3))
print(z)

z[1, :] = 5
z[:, -1] = 7
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]


In [8]:
print(z.dtype)

float64


In [9]:
z = np.zeros((3, 3), dtype = np.int64)
print(z)
print(z.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
int64


### Mathematical Operations  
(Broadcasting)

In [10]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [11]:
#Element-wise addition
print(x + y)
print(np.add(x, y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [12]:
print(x - y)
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [13]:
print(x * y)
print(np.multiply(x, y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [14]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [15]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


### Matrix Multiplication and Dot Product

In [16]:
print(x)
print(y)

print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### Multiplication of Vectors => Scalar

In [17]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, -1])
print(a.dot(b))

10


In [18]:
print(a)
print(sum(a))

[1 2 3 4]
10


In [19]:
print(x)
print(np.sum(x))

# sum along column
print(np.sum(x, axis = 0))
# sum along row
print(np.sum(x, axis = 1))

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


### Stacking of Arrays

In [20]:
print(a)
b = a ** 2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [21]:
print(np.stack((a, b), axis = 0))
print(np.stack((a, b), axis = 1))

[[ 1  2  3  4]
 [ 1  4  9 16]]
[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]


### Reshape a Numpy Array

In [22]:
anew = np.stack((a, b), axis = 0)
print(anew)
print(anew.shape)

[[ 1  2  3  4]
 [ 1  4  9 16]]
(2, 4)


In [23]:
anew = anew.reshape((4, 2))
print(anew)

[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


In [24]:
anew = anew.reshape((2, 4))
print(anew)

[[ 1  2  3  4]
 [ 1  4  9 16]]


In [25]:
anew = anew.reshape((8, 1))
print(anew)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 1]
 [ 4]
 [ 9]
 [16]]


In [26]:
anew = anew.reshape((1, 8))
print(anew)

[[ 1  2  3  4  1  4  9 16]]


In [27]:
anew = anew.reshape((4, -1)) # Automatically replaces -1 by required number
print(anew)

[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


## Numpy Random Module
- rand: Random values in a given shape
- randn: Return a sample (or samples) from the "standard normal" distribution
- randint: Return random integers from low (inclusive) to high (exclusive)
- random: Return random floats in the half-open interval [0.0, 1.0)
- choice: Generates a random sample from a given 1-D array
- Shuffle: Shuffles the contents of a sequence

#### np.arange (not part of Numpy)

In [28]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [29]:
# Random number generates are pseudo-random generators
# If we want to replicate the random series :
# np.random.seed(1)
# To store the state of the random numbers
np.random.shuffle(a)
print(a)

[10  5  7 11  8 14  9 13 12  6]


In [30]:
a = np.random.rand(2, 3)
print(a)

[[0.79584653 0.71615216 0.45457181]
 [0.28267115 0.16870412 0.48078154]]


In [31]:
a = np.random.randn(2, 3)
print(a)

[[-0.30501623  0.96444135 -0.30542157]
 [ 1.85096085  0.16039614 -0.42381657]]


In [32]:
a = np.random.randint(5, 10)
print(a)

7


In [33]:
# Randomly pick one element from an array
element = np.random.choice([2, 4, 1, 6, 5, 9])
print(element)

5


In [63]:
a = np.array([3, 2, 1, 6, 3, 1, 2])
print(np.unique(a, return_counts = True))

(array([1, 2, 3, 6]), array([2, 2, 2, 1]))


In [64]:
# Program to print element with highest frequency

In [65]:
a = [1, 4, 3, 2, 7, 1, 5, 4, -1, 4, 3, 4]
b = np.unique(a, return_counts = True)
print(b[0][np.argmax(b[1])])

4


## Some more Numpy Functions
- min, max
- mean
- median
- average
- variance
- standard distribution
- prod

In [59]:
a = np.array([[1, 2, 3, 4], [7, 6, 2, 0]])
print(a)
print(np.max(a))
print(np.min(a))
print(np.argmin(a)) # Index of minimum element
print(np.min(a, axis = 0))
print(np.min(a, axis = 1))

[[1 2 3 4]
 [7 6 2 0]]
7
0
7
[1 2 2 0]
[1 0]


In [41]:
b = np.array([1, 2, 3, 4, 5])
print(np.mean(b))
print(np.sum(b) / 5)
print(np.mean(a, axis = 0))
print(np.mean(a, axis = 1))
print(np.prod(b))

3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]
120


In [36]:
c = np.array([1, 5, 4, 2, 0])
print(np.median(c))

2.0


In [37]:
# Mean vs Average
# Average is weighted
print(np.mean(c))
w = np.array([1, 2, 3, 4, 5])
print(np.average(c, weights = w))
w = np.ones(5)
print(np.average(c, weights = w))

2.4
2.066666666666667
2.4


Standard Deviation = sqrt(sigma((x(i) - mean)^2) / N)   
Variance = (S.D.)^2  
Variance = mean(x^2) - (mean(x))^2

In [38]:
u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c - u)**2))
print(myStd)

# Inbuilt Function
dev = np.std(c)
print(dev)

# Variance
print(myStd**2)
print(np.var(c))

1.854723699099141
1.854723699099141
3.440000000000001
3.4400000000000004


### Standard Deviation in a Running Stream

In [57]:
from math import sqrt

num = input()
sum = 0
sum2 = 0
n = 0
while num != '' :
    num = int(num)
    sum += num
    sum2 += num**2
    n += 1
    mean = sum / n
    stdDev = sqrt((sum2 - sum) / n)
    print(mean)
    print(stdDev)
    num = input()

1
1.0
0.0
2
1.5
1.0
3
2.0
1.632993161855452



In [40]:
print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [46]:
y = np.array([[1, 2, 3], [4, 5, 6]])
# print(np.tolist(y))
print(np.size(y))
print(y.tolist())

6
[[1, 2, 3], [4, 5, 6]]


In [48]:
a = np.random.randint(0,15, size=(4,4))
print(a[np.where((a >= 5) & (a <= 10))])
print(a[(a >= 5) & (a <= 10)])

[ 5  7 10  7  5  5  6  5]
[ 5  7 10  7  5  5  6  5]


In [50]:
a = np.arange(1,17).reshape(4,4)
b = np.arange(17,33).reshape(4,4)
print(np.hstack((a,b)))
print(np.concatenate((a,b), axis = 0))
print(np.concatenate((a,b), axis = 1))

[[ 1  2  3  4 17 18 19 20]
 [ 5  6  7  8 21 22 23 24]
 [ 9 10 11 12 25 26 27 28]
 [13 14 15 16 29 30 31 32]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]
[[ 1  2  3  4 17 18 19 20]
 [ 5  6  7  8 21 22 23 24]
 [ 9 10 11 12 25 26 27 28]
 [13 14 15 16 29 30 31 32]]


In [55]:
img = np.arange(3*3*3).reshape(3,3,3)
print(img)
print()
print()
print(img[::-1])
print()
print()
print(img[[2,1,0], :, :])
print()
print()
print(img[:, ::-1])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


[[[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]]


[[[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]]


[[[ 6  7  8]
  [ 3  4  5]
  [ 0  1  2]]

 [[15 16 17]
  [12 13 14]
  [ 9 10 11]]

 [[24 25 26]
  [21 22 23]
  [18 19 20]]]
