In [2]:
import pandas as pd
import numpy as np

## Pandas
- Dataframe- Special Object to store data in tabular form (rows and columns)

In [7]:
# Try to create a data frame

user_data = {
    "MarksA": np.random.randint(1, 100, 5),
    "MarksB": np.random.randint(50, 100, 5),
    "MarksC": np.random.randint(1, 100, 5),
}

user_data

{'MarksA': array([46, 61, 92, 10, 90]),
 'MarksB': array([92, 51, 53, 97, 85]),
 'MarksC': array([37, 59,  6, 12,  9])}

In [9]:
df = pd.DataFrame(user_data)

In [12]:
print(df)

   MarksA  MarksB  MarksC
0      46      92      37
1      61      51      59
2      92      53       6
3      10      97      12
4      90      85       9


In [13]:
df.head(n = 3)

MarksA  MarksB  MarksC
0      46      92      37
1      61      51      59
2      92      53       6

In [15]:
print(df.columns)

Index(['MarksA', 'MarksB', 'MarksC'], dtype='object')


In [16]:
df = pd.DataFrame(user_data, dtype = 'float32')

In [17]:
df

MarksA  MarksB  MarksC
0    46.0    92.0    37.0
1    61.0    51.0    59.0
2    92.0    53.0     6.0
3    10.0    97.0    12.0
4    90.0    85.0     9.0

In [18]:
df.to_csv('marks.csv')

In [22]:
my_data = pd.read_csv('marks.csv')
print(my_data)

   Unnamed: 0  MarksA  MarksB  MarksC
0           0    46.0    92.0    37.0
1           1    61.0    51.0    59.0
2           2    92.0    53.0     6.0
3           3    10.0    97.0    12.0
4           4    90.0    85.0     9.0


In [23]:
my_data = my_data.drop(columns = ['Unnamed: 0'])
print(my_data)

   MarksA  MarksB  MarksC
0    46.0    92.0    37.0
1    61.0    51.0    59.0
2    92.0    53.0     6.0
3    10.0    97.0    12.0
4    90.0    85.0     9.0


In [26]:
my_data.describe()

MarksA    MarksB     MarksC
count   5.000000   5.00000   5.000000
mean   59.800000  75.60000  24.600000
std    33.988233  21.97271  22.831995
min    10.000000  51.00000   6.000000
25%    46.000000  53.00000   9.000000
50%    61.000000  85.00000  12.000000
75%    90.000000  92.00000  37.000000
max    92.000000  97.00000  59.000000

In [27]:
my_data.tail(n = 3)

MarksA  MarksB  MarksC
2    92.0    53.0     6.0
3    10.0    97.0    12.0
4    90.0    85.0     9.0

In [28]:
# iloc -> integer location
my_data.iloc[3]

MarksA    10.0
MarksB    97.0
MarksC    12.0
Name: 3, dtype: float64

In [29]:
df.iloc[3, 1]

97.0

In [30]:
df.iloc[3][1]

97.0

In [31]:
idx = df.columns.get_loc('MarksB')
print(idx)
df.iloc[3, idx]

1


97.0

In [32]:
df.iloc[3, 1:3]

MarksB    97.0
MarksC    12.0
Name: 3, dtype: float32

In [33]:
idx = [df.columns.get_loc('MarksB'), df.columns.get_loc('MarksC')]
print(idx)
df.iloc[3, idx]

[1, 2]


MarksB    97.0
MarksC    12.0
Name: 3, dtype: float32

In [35]:
df.iloc[:3, idx]

MarksB  MarksC
0    92.0    37.0
1    51.0    59.0
2    53.0     6.0

In [36]:
df.iloc[:3, [1, 2]]

MarksB  MarksC
0    92.0    37.0
1    51.0    59.0
2    53.0     6.0

In [37]:
# Sort data frame

In [38]:
my_data

MarksA  MarksB  MarksC
0    46.0    92.0    37.0
1    61.0    51.0    59.0
2    92.0    53.0     6.0
3    10.0    97.0    12.0
4    90.0    85.0     9.0

In [39]:
my_data.sort_values(by = ['MarksA'], ascending = True)

MarksA  MarksB  MarksC
3    10.0    97.0    12.0
0    46.0    92.0    37.0
1    61.0    51.0    59.0
4    90.0    85.0     9.0
2    92.0    53.0     6.0

In [40]:
my_data.sort_values(by = ['MarksA'], ascending = False)

MarksA  MarksB  MarksC
2    92.0    53.0     6.0
4    90.0    85.0     9.0
1    61.0    51.0    59.0
0    46.0    92.0    37.0
3    10.0    97.0    12.0

In [42]:
# 1st priority to C and then A
my_data.sort_values(by = ['MarksC', 'MarksA'], ascending = False)

MarksA  MarksB  MarksC
1    61.0    51.0    59.0
0    46.0    92.0    37.0
3    10.0    97.0    12.0
4    90.0    85.0     9.0
2    92.0    53.0     6.0

In [44]:
data_array = my_data.values

In [47]:
print(type(my_data))
print(my_data.shape)

<class 'pandas.core.frame.DataFrame'>
(5, 3)


In [48]:
print(type(data_array))
print(data_array)
print(data_array.shape)

<class 'numpy.ndarray'>
[[46. 92. 37.]
 [61. 51. 59.]
 [92. 53.  6.]
 [10. 97. 12.]
 [90. 85.  9.]]
(5, 3)


In [49]:
data_array[2][2]

6.0

In [50]:
# Numpy arrays back into data frame

In [51]:
new_df = pd.DataFrame(data_array, dtype = 'int32', columns = ['Phy', 'Chem', 'Math'])

In [52]:
new_df

Phy  Chem  Math
0   46    92    37
1   61    51    59
2   92    53     6
3   10    97    12
4   90    85     9

In [54]:
new_df.to_csv('PCM.csv', index = False)

In [55]:
pcm = pd.read_csv('PCM.csv')
print(pcm)

   Phy  Chem  Math
0   46    92    37
1   61    51    59
2   92    53     6
3   10    97    12
4   90    85     9
