In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('mushrooms.csv')

In [3]:
df.head(n = 10)

type cap_shape cap_surface cap_color bruises odor gill_attachment  \
0    p         x           s         n       t    p               f   
1    e         x           s         y       t    a               f   
2    e         b           s         w       t    l               f   
3    p         x           y         w       t    p               f   
4    e         x           s         g       f    n               f   
5    e         x           y         y       t    a               f   
6    e         b           s         w       t    a               f   
7    e         b           y         w       t    l               f   
8    p         x           y         w       t    p               f   
9    e         b           s         y       t    a               f   

  gill_spacing gill_size gill_color  ... stalk_surface_below_ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   
5            c         b          n  ...                        s   
6            c         b          g  ...                        s   
7            c         b          n  ...                        s   
8            c         n          p  ...                        s   
9            c         b          g  ...                        s   

  stalk_color_above_ring stalk_color_below_ring veil_type veil_color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   
5                      w                      w         p          w   
6                      w                      w         p          w   
7                      w                      w         p          w   
8                      w                      w         p          w   
9                      w                      w         p          w   

  ring_number ring_type spore_print_color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  
5           o         p                 k          n       g  
6           o         p                 k          n       m  
7           o         p                 n          s       m  
8           o         p                 k          v       g  
9           o         p                 k          s       m  

[10 rows x 23 columns]

In [4]:
df.shape

(8124, 23)

In [5]:
df.describe()

type cap_shape cap_surface cap_color bruises  odor gill_attachment  \
count   8124      8124        8124      8124    8124  8124            8124   
unique     2         6           4        10       2     9               2   
top        e         x           y         n       f     n               f   
freq    4208      3656        3244      2284    4748  3528            7914   

       gill_spacing gill_size gill_color  ... stalk_surface_below_ring  \
count          8124      8124       8124  ...                     8124   
unique            2         2         12  ...                        4   
top               c         b          b  ...                        s   
freq           6812      5612       1728  ...                     4936   

       stalk_color_above_ring stalk_color_below_ring veil_type veil_color  \
count                    8124                   8124      8124       8124   
unique                      9                      9         1          4   
top                         w                      w         p          w   
freq                     4464                   4384      8124       7924   

       ring_number ring_type spore_print_color population habitat  
count         8124      8124              8124       8124    8124  
unique           3         5                 9          6       7  
top              o         p                 w          v       d  
freq          7488      3968              2388       4040    3148  

[4 rows x 23 columns]

### Converting categorical data into numerical data

In [6]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [7]:
le = LabelEncoder()
# Applies transformation on each column
ds = df.apply(le.fit_transform)

In [8]:
# dfx = df.iloc[:, 1:]
# dfy = df.iloc[:, [0]]
# print(type(dfx), type(dfy))

In [9]:
# lex = LabelEncoder()
# ley = LabelEncoder()

In [10]:
# dfx = dfx.apply(lex.fit_transform)
# dfy = dfy.apply(ley.fit_transform)

In [11]:
# ley.inverse_transform([1])

In [12]:
ds.head(n = 10)

type  cap_shape  cap_surface  cap_color  bruises  odor  gill_attachment  \
0     1          5            2          4        1     6                1   
1     0          5            2          9        1     0                1   
2     0          0            2          8        1     3                1   
3     1          5            3          8        1     6                1   
4     0          5            2          3        0     5                1   
5     0          5            3          9        1     0                1   
6     0          0            2          8        1     0                1   
7     0          0            3          8        1     3                1   
8     1          5            3          8        1     6                1   
9     0          0            2          9        1     0                1   

   gill_spacing  gill_size  gill_color  ...  stalk_surface_below_ring  \
0             0          1           4  ...                         2   
1             0          0           4  ...                         2   
2             0          0           5  ...                         2   
3             0          1           5  ...                         2   
4             1          0           4  ...                         2   
5             0          0           5  ...                         2   
6             0          0           2  ...                         2   
7             0          0           5  ...                         2   
8             0          1           7  ...                         2   
9             0          0           2  ...                         2   

   stalk_color_above_ring  stalk_color_below_ring  veil_type  veil_color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   
5                       7                       7          0           2   
6                       7                       7          0           2   
7                       7                       7          0           2   
8                       7                       7          0           2   
9                       7                       7          0           2   

   ring_number  ring_type  spore_print_color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  
5            1          4                  2           2        1  
6            1          4                  2           2        3  
7            1          4                  3           3        3  
8            1          4                  2           4        1  
9            1          4                  2           3        3  

[10 rows x 23 columns]

In [13]:
data = ds.values
print(data.shape)
print(type(data))
print(data[0])
y = data[:, 0]
X = data[:, 1:]

(8124, 23)
<class 'numpy.ndarray'>
[1 5 2 4 1 6 1 0 1 4 0 3 2 2 7 7 0 2 1 4 2 3 5]


### Breaking data into train and test data

In [14]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [15]:
x_train[0], y_train[0]

(array([5, 0, 4, 0, 5, 1, 1, 0, 4, 1, 3, 0, 2, 7, 7, 0, 2, 1, 0, 2, 0, 1]), 0)

In [16]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(6499, 22) (6499,)
(1625, 22) (1625,)


In [17]:
np.unique(y_train)

array([0, 1])

In [18]:
# dfx = ds.iloc[:, 0]

In [19]:
# dfx.head()

### Building the Classifier

In [20]:
def prior_prob(y_train, label) :
    return np.sum(y_train == label) / y_train.shape[0]

In [21]:
def cond_prob(x_train, y_train, feature_col, feature_val, label) :
    x_filtered = x_train[y_train == label]
    numerator = np.sum(x_filtered[:, feature_col] == feature_val)
    denominator = np.sum(y_train == label)
    return numerator / denominator

In [22]:
def likelihood(x_train, y_train, xtest, label) :
    lk = 1.0
    for f in range(x_train.shape[1]) :
        cond = cond_prob(x_train, y_train, f, xtest[f], label)
        lk *= cond
    return lk

In [25]:
def predict(x_train, y_train, xtest) :
    classes = np.unique(y_train)
    n_features = x_train.shape[1]
    
    post_probs = []
    
    for label in classes :
        lk = likelihood(x_train, y_train, xtest, label)
        prior = prior_prob(y_train, label)
        post = lk * prior
        post_probs.append(post)
        
    pred = np.argmax(post_probs)
    return pred

In [26]:
output = predict(x_train, y_train, x_test[1])
print(output, y_test[1])

1 1


In [33]:
def score(x_train, y_train, x_test, y_test) :
    pred = []
    
    for i in range(x_test.shape[0]) :
        pred_label = predict(x_train, y_train, x_test[i])
        pred.append(pred_label)
    
    pred = np.array(pred)
    
    accuracy = np.sum(pred == y_test) / y_test.shape[0]
    return accuracy

In [34]:
print(score(x_train, y_train, x_test, y_test))

0.9987692307692307
